In [33]:
#Завдання 1
import numpy as np
#1
A=np.array([[1,2],[4,-1]])
B=np.array([[2,-3],[-4,1]])
print(f"Знайти C = AB-BA = \n", A.dot(B)-B.dot(A))
#2
a = np.array([[-1, 0, 2], [0, 1, 0], [1, 2, -1]])
print(f"Піднести матрицю до степеня: \n", np.linalg.matrix_power(a, 2))
#3
b = np.array([[5, 8, -4], [6, 9, -5], [4, 7, -3]])
c = np.array([[3, 2, 5], [4, -1, 3], [9, 6, 5]])
print(f"Знайти добуток матриць: \n", b.dot(c))
#4
d = np.array([[2, 4, 5], [1, 1, 2], [2, 4, 3]])
print(f"Обчислити визначник: \n", np.linalg.det(d))
#5
d2 = np.array([[2, 3, 4, 1], [1, 2, 3, 4], [3, 4, 1, 2], [4, 1, 2, 3]])
print(f"Обчислити визначник: \n", np.linalg.det(d2))
#6
d3 = np.array([[2, 1, 0, 0], [3, 2, 0, 0], [1, 1, 3, 4], [2, -1, 2, 3]])
print(f"Знайти обернену матрицю: \n", np.linalg.inv(d3))
#7
d4 = np.array([[1, 2, 3, 4], [3, -1, 2, 5], [1, 2, 3, 4], [1, 3, 4, 5]])
print(f"Визначити ранг матриці: \n", np.linalg.matrix_rank(d4))

Знайти C = AB-BA = 
 [[ 4 -8]
 [12 -4]]
Піднести матрицю до степеня: 
 [[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]
Знайти добуток матриць: 
 [[ 11 -22  29]
 [  9 -27  32]
 [ 13 -17  26]]
Обчислити визначник: 
 4.0
Обчислити визначник: 
 -160.00000000000009
Знайти обернену матрицю: 
 [[  2.  -1.   0.   0.]
 [ -3.   2.   0.   0.]
 [ 31. -19.   3.  -4.]
 [-23.  14.  -2.   3.]]
Визначити ранг матриці: 
 2


In [34]:
#8.	Розв’язати систему лінійних рівнянь методом Крамера
import numpy as np
ar = np.matrix('7 3 -6; 7 9 -9; 2 -4 -9')
br = np.matrix('-1; 5; 28')
def kram(ar,br):
    det_a = np.linalg.det(ar)
    if det_a != 0:
       a1 = np.matrix(ar)
       a2 = np.matrix(ar)
       a3 = np.matrix(ar)
       a1[:, 0] = br
       a2[:, 1] = br
       a3[:, 2] = br
       x = np.linalg.det(a1)/det_a
       y =np.linalg.det(a2)/det_a
       z= np.linalg.det(a3)/det_a
       print('Розв*язування системи лінійних алгебраїчних рівнянь методом Крамера')
       print('x=',x.round(3),'y=',y.round(3),'z=',z.round(3)) 
    else:
        print('Визначник дорівнює нулю, система не має розв*язків')
    return x,y,z
kram(ar,br)
print('Перевіряємо правильність рішення\n', np.linalg.solve(ar,br).round(3)) 

Розв*язування системи лінійних алгебраїчних рівнянь методом Крамера
x= -2.765 y= -0.706 z= -3.412
Перевіряємо правильність рішення
 [[-2.765]
 [-0.706]
 [-3.412]]


In [32]:
import numpy as np
#Завдання 2
#matrix_A = np.array(np.random.randint(0,10, size=(3,4)))
matrix_A = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
print(f"matrix_A = \n", matrix_A)

means_r=np.mean(matrix_A, axis=1)
print("Середнє значення рядків = \n", means_r)
print("Найнижче значення серед середніх значень для кожного рядка матриці =", means_r.min())

matrix_A = 
 [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
Середнє значення рядків = 
 [2. 3. 4. 5.]
Найнижче значення серед середніх значень для кожного рядка матриці = 2.0
